version: 2
jobs:
  build_and_test:
    working_directory: ~/wis-application
    docker:
      - image: circleci/python:2.7
        environment:
          SERVER_ENV: test
    steps:
      - checkout
      - restore_cache:
          key: wis-application-dependencies-{{ checksum "requirements.txt" }}
      - run:
          name: install dependencies
          command: |
            mkdir -p ./venv
            virtualenv ./venv
            . venv/bin/activate
            pip install -r requirements.txt
      - save_cache:
          key: wis-application-dependencies-{{ checksum "requirements.txt" }}
          paths:
            - ./venv
      - run:
          name: run tests
          command: |
            . venv/bin/activate
            # python manage.py test
            echo 'todo: add tests'
  deploy_to_staging:
    working_directory: ~/wis-application
    docker:
      - image: circleci/python:2.7
    steps:
      - checkout
      - deploy:
          name: deploy to heroku
          command: git push https://heroku:$HEROKU_API_KEY@git.heroku.com/wis-application-staging.git master
  deploy_to_production:
    working_directory: ~/wis-application
    docker:
      - image: circleci/python:2.7
    steps:
      - checkout
      - deploy:
          name: deploy to heroku
          command: git push https://heroku:$HEROKU_API_KEY@git.heroku.com/wis-application-production.git master

workflows:
  version: 2
  build_test_deploy:
    jobs:
      - build_and_test
      - deploy_to_staging:
          requires:
            - build_and_test
          filters:
            branches:
              only:
                - master
                - /feature.*/
      - deploy_to_production:
          requires:
            - build_and_test
          filters:
            tags:
              only:
                - /v.*/
            branches:
              ignore:
                - /.*/
