# Generated by Django 2.1.1 on 2018-09-02 23:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='allowed_user',
            name='email',
            field=models.TextField(unique=True),
        ),
        migrations.AlterField(
            model_name='volunteer_date_registration',
            name='cancel_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
