# Generated by Django 2.1.1 on 2018-09-03 20:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0002_auto_20180902_2320'),
    ]

    operations = [
        migrations.AddField(
            model_name='wis_user',
            name='max_registrations',
            field=models.IntegerField(default=8),
        ),
    ]
